const LANGUAGE_MAP: Record<string, string> = {
  python: "Python",
  javascript: "JavaScript",
  typescript: "TypeScript",
  typescriptreact: "TypeScript React",
  javascriptreact: "JavaScript React",
  java: "Java",
  csharp: "C#",
  cpp: "C++",
  c: "C",
  go: "Go",
  rust: "Rust",
  ruby: "Ruby",
  php: "PHP",
  swift: "Swift",
  kotlin: "Kotlin",
  scala: "Scala",
  dart: "Dart",
  r: "R",
  lua: "Lua",
  perl: "Perl",
  haskell: "Haskell",
  elixir: "Elixir",
  clojure: "Clojure",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "Less",
  json: "JSON",
  jsonc: "JSON with Comments",
  yaml: "YAML",
  toml: "TOML",
  xml: "XML",
  markdown: "Markdown",
  plaintext: "Plain Text",
  shellscript: "Shell Script",
  powershell: "PowerShell",
  dockerfile: "Dockerfile",
  sql: "SQL",
  graphql: "GraphQL",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  zig: "Zig",
  nim: "Nim",
  ocaml: "OCaml",
  fsharp: "F#",
  julia: "Julia",
  objective_c: "Objective-C",
  coffeescript: "CoffeeScript",
  vb: "Visual Basic",
  "vb.net": "VB.NET",
  dockercompose: "Docker Compose",
  terraform: "Terraform",
  prisma: "Prisma",
  solidity: "Solidity",
  wasm: "WebAssembly",
  handlebars: "Handlebars",
  jade: "Pug",
  pug: "Pug",
  razor: "Razor",
  erb: "Ruby",
  gemfile: "Ruby",
  cuda_cpp: "CUDA",
  hlsl: "HLSL",
  glsl: "GLSL",
  shaderlab: "ShaderLab",
  matlab: "MATLAB",
  make: "Makefile",
  cmake: "CMake",
  ini: "INI",
  properties: "Properties",
  gitignore: "Git Ignore",
  ignore: "Ignore",
  log: "Log",
  csv: "CSV",
  diff: "Diff",
  patch: "Diff",
  bibtex: "BibTeX",
  latex: "LaTeX",
  tex: "TeX",
  rst: "ReStructuredText",
  adoc: "AsciiDoc",
  asciidoc: "AsciiDoc",
  erlang: "Erlang",
  groovy: "Groovy",
  lisp: "Lisp",
  scheme: "Scheme",
  racket: "Racket",
  prolog: "Prolog",
  fortran: "Fortran",
  cobol: "COBOL",
  pascal: "Pascal",
  verilog: "Verilog",
  vhdl: "VHDL",
  systemverilog: "SystemVerilog",
  stata: "Stata",
  sas: "SAS",
  awk: "Awk",
  bat: "Batch",
  cmd: "Batch",
  ps1: "PowerShell",
  psd1: "PowerShell",
  psm1: "PowerShell",
  hcl: "HCL",
  nginx: "Nginx",
  apacheconf: "Apache",
  redis: "Redis",
  mongo: "MongoDB",
  mdx: "MDX",
  wgsl: "WGSL",
  shader: "GLSL",
  gdscript: "GDScript",
  gdresource: "Godot",
  gdshader: "Godot",
  v: "V",
  crystal: "Crystal",
  d: "D",
  odin: "Odin",
  mojo: "Mojo",
  nix: "Nix",
  starlark: "Starlark",
  bazel: "Starlark",
  bzl: "Starlark",
  containerfile: "Dockerfile",
};

export function getLanguageDisplayName(languageId: string): string {
  const id = languageId.toLowerCase();
  return (
    LANGUAGE_MAP[id] ??
    LANGUAGE_MAP[languageId] ??
    languageId.charAt(0).toUpperCase() + languageId.slice(1)
  );
}
