const LANGUAGE_MAP: Record<string, string> = {
  python: "Python",
  javascript: "JavaScript",
  typescript: "TypeScript",
  typescriptreact: "TypeScript React",
  javascriptreact: "JavaScript React",
  java: "Java",
  csharp: "C#",
  cpp: "C++",
  c: "C",
  go: "Go",
  rust: "Rust",
  ruby: "Ruby",
  php: "PHP",
  swift: "Swift",
  kotlin: "Kotlin",
  scala: "Scala",
  dart: "Dart",
  r: "R",
  lua: "Lua",
  perl: "Perl",
  haskell: "Haskell",
  elixir: "Elixir",
  clojure: "Clojure",
  html: "HTML",
  css: "CSS",
  scss: "SCSS",
  less: "Less",
  json: "JSON",
  jsonc: "JSON with Comments",
  yaml: "YAML",
  toml: "TOML",
  xml: "XML",
  markdown: "Markdown",
  plaintext: "Plain Text",
  shellscript: "Shell Script",
  powershell: "PowerShell",
  dockerfile: "Dockerfile",
  sql: "SQL",
  graphql: "GraphQL",
  vue: "Vue",
  svelte: "Svelte",
  astro: "Astro",
  zig: "Zig",
  nim: "Nim",
  ocaml: "OCaml",
  fsharp: "F#",
  julia: "Julia",
  objective_c: "Objective-C",
  coffeescript: "CoffeeScript",
};

export function getLanguageDisplayName(languageId: string): string {
  return (
    LANGUAGE_MAP[languageId] ??
    languageId.charAt(0).toUpperCase() + languageId.slice(1)
  );
}
